[package]
name = "hexcolor"
version = "0.1.0"
edition = "2021"

[dependencies]
hexmacros = { workspace = true }
serde = { workspace = true }
bytemuck = { workspace = true }
glam = { workspace = true }