[package]
name = "hexmacros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
hashbrown = "0.15.2"
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.96", features = ["extra-traits"] }
