[package]
name = "hexhash"
version = "0.1.0"
edition = "2021"

[dependencies]
hexio = { path = "../hexio" }
hexmacros = { workspace = true }
bytemuck = { workspace = true }
sha2 = "0.10.8"
twox-hash = "2.1.0"
blake3 = "1.5.5"