[package]
name = "hexhash"
version = "0.1.0"
edition = "2021"

[dependencies]
hexio = { path = "../hexio" }
hexmacros = { path = "../hexmacros" }
bytemuck = { version = "1.18.0", features = ["derive"] }
sha2 = "0.10.8"
twox-hash = "2.1.0"
blake3 = "1.5.5"