#[rustfmt::skip]
macro_rules! html_colors {
    ($macro:path) => {
        $macro!{
["Alice Blue"               AliceBlue               ALICE_BLUE                  alice_blue                  aliceblue               ALICEBLUE               "F0F8FF"    RGB(240, 248, 255)  ]
["Antique White"            AntiqueWhite            ANTIQUE_WHITE               antique_white               antiquewhite            ANTIQUEWHITE            "FAEBD7"    RGB(250, 235, 215)  ]
["Aqua"                     Aqua                    AQUA                        aqua                        aqua                    AQUA                    "00FFFF"    RGB(0, 255, 255)    ]
["Aquamarine"               Aquamarine              AQUAMARINE                  aquamarine                  aquamarine              AQUAMARINE              "7FFFD4"    RGB(127, 255, 212)  ]
["Azure"                    Azure                   AZURE                       azure                       azure                   AZURE                   "F0FFFF"    RGB(240, 255, 255)  ]
["Beige"                    Beige                   BEIGE                       beige                       beige                   BEIGE                   "F5F5DC"    RGB(245, 245, 220)  ]
["Bisque"                   Bisque                  BISQUE                      bisque                      bisque                  BISQUE                  "FFE4C4"    RGB(255, 228, 196)  ]
["Black"                    Black                   BLACK                       black                       black                   BLACK                   "000000"    RGB(0, 0, 0)        ]
["Blanched Almond"          BlanchedAlmond          BLANCHED_ALMOND             blanched_almond             blanchedalmond          BLANCHEDALMOND          "FFEBCD"    RGB(255, 235, 205)  ]
["Blue"                     Blue                    BLUE                        blue                        blue                    BLUE                    "0000FF"    RGB(0, 0, 255)      ]
["Blue Violet"              BlueViolet              BLUE_VIOLET                 blue_violet                 blueviolet              BLUEVIOLET              "8A2BE2"    RGB(138, 43, 226)   ]
["Brown"                    Brown                   BROWN                       brown                       brown                   BROWN                   "A52A2A"    RGB(165, 42, 42)    ]
["Burly Wood"               BurlyWood               BURLY_WOOD                  burly_wood                  burlywood               BURLYWOOD               "DEB887"    RGB(222, 184, 135)  ]
["Cadet Blue"               CadetBlue               CADET_BLUE                  cadet_blue                  cadetblue               CADETBLUE               "5F9EA0"    RGB(95, 158, 160)   ]
["Chartreuse"               Chartreuse              CHARTREUSE                  chartreuse                  chartreuse              CHARTREUSE              "7FFF00"    RGB(127, 255, 0)    ]
["Chocolate"                Chocolate               CHOCOLATE                   chocolate                   chocolate               CHOCOLATE               "D2691E"    RGB(210, 105, 30)   ]
["Coral"                    Coral                   CORAL                       coral                       coral                   CORAL                   "FF7F50"    RGB(255, 127, 80)   ]
["Cornflower Blue"          CornflowerBlue          CORNFLOWER_BLUE             cornflower_blue             cornflowerblue          CORNFLOWERBLUE          "6495ED"    RGB(100, 149, 237)  ]
["Cornsilk"                 Cornsilk                CORNSILK                    cornsilk                    cornsilk                CORNSILK                "FFF8DC"    RGB(255, 248, 220)  ]
["Crimson"                  Crimson                 CRIMSON                     crimson                     crimson                 CRIMSON                 "DC143C"    RGB(220, 20, 60)    ]
["Cyan"                     Cyan                    CYAN                        cyan                        cyan                    CYAN                    "00FFFF"    RGB(0, 255, 255)    ]
["Dark Blue"                DarkBlue                DARK_BLUE                   dark_blue                   darkblue                DARKBLUE                "00008B"    RGB(0, 0, 139)      ]
["Dark Cyan"                DarkCyan                DARK_CYAN                   dark_cyan                   darkcyan                DARKCYAN                "008B8B"    RGB(0, 139, 139)    ]
["Dark Goldenrod"           DarkGoldenrod           DARK_GOLDENROD              dark_goldenrod              darkgoldenrod           DARKGOLDENROD           "B8860B"    RGB(184, 134, 11)   ]
["Dark Gray"                DarkGray                DARK_GRAY                   dark_gray                   darkgray                DARKGRAY                "A9A9A9"    RGB(169, 169, 169)  ]
["Dark Green"               DarkGreen               DARK_GREEN                  dark_green                  darkgreen               DARKGREEN               "006400"    RGB(0, 100, 0)      ]
["Dark Khaki"               DarkKhaki               DARK_KHAKI                  dark_khaki                  darkkhaki               DARKKHAKI               "BDB76B"    RGB(189, 183, 107)  ]
["Dark Magenta"             DarkMagenta             DARK_MAGENTA                dark_magenta                darkmagenta             DARKMAGENTA             "8B008B"    RGB(139, 0, 139)    ]
["Dark Olive Green"         DarkOliveGreen          DARK_OLIVE_GREEN            dark_olive_green            darkolivegreen          DARKOLIVEGREEN          "556B2F"    RGB(85, 107, 47)    ]
["Dark Orange"              DarkOrange              DARK_ORANGE                 dark_orange                 darkorange              DARKORANGE              "FF8C00"    RGB(255, 140, 0)    ]
["Dark Orchid"              DarkOrchid              DARK_ORCHID                 dark_orchid                 darkorchid              DARKORCHID              "9932CC"    RGB(153, 50, 204)   ]
["Dark Red"                 DarkRed                 DARK_RED                    dark_red                    darkred                 DARKRED                 "8B0000"    RGB(139, 0, 0)      ]
["Dark Salmon"              DarkSalmon              DARK_SALMON                 dark_salmon                 darksalmon              DARKSALMON              "E9967A"    RGB(233, 150, 122)  ]
["Dark Sea Green"           DarkSeaGreen            DARK_SEA_GREEN              dark_sea_green              darkseagreen            DARKSEAGREEN            "8FBC8F"    RGB(143, 188, 143)  ]
["Dark Slate Blue"          DarkSlateBlue           DARK_SLATE_BLUE             dark_slate_blue             darkslateblue           DARKSLATEBLUE           "483D8B"    RGB(72, 61, 139)    ]
["Dark Slate Gray"          DarkSlateGray           DARK_SLATE_GRAY             dark_slate_gray             darkslategray           DARKSLATEGRAY           "2F4F4F"    RGB(47, 79, 79)     ]
["Dark Turquoise"           DarkTurquoise           DARK_TURQUOISE              dark_turquoise              darkturquoise           DARKTURQUOISE           "00CED1"    RGB(0, 206, 209)    ]
["Dark Violet"              DarkViolet              DARK_VIOLET                 dark_violet                 darkviolet              DARKVIOLET              "9400D3"    RGB(148, 0, 211)    ]
["Deep Pink"                DeepPink                DEEP_PINK                   deep_pink                   deeppink                DEEPPINK                "FF1493"    RGB(255, 20, 147)   ]
["Deep Sky Blue"            DeepSkyBlue             DEEP_SKY_BLUE               deep_sky_blue               deepskyblue             DEEPSKYBLUE             "00BFFF"    RGB(0, 191, 255)    ]
["Dim Gray"                 DimGray                 DIM_GRAY                    dim_gray                    dimgray                 DIMGRAY                 "696969"    RGB(105, 105, 105)  ]
["Dodger Blue"              DodgerBlue              DODGER_BLUE                 dodger_blue                 dodgerblue              DODGERBLUE              "1E90FF"    RGB(30, 144, 255)   ]
["Fire Brick"               FireBrick               FIRE_BRICK                  fire_brick                  firebrick               FIREBRICK               "B22222"    RGB(178, 34, 34)    ]
["Floral White"             FloralWhite             FLORAL_WHITE                floral_white                floralwhite             FLORALWHITE             "FFFAF0"    RGB(255, 250, 240)  ]
["Forest Green"             ForestGreen             FOREST_GREEN                forest_green                forestgreen             FORESTGREEN             "228B22"    RGB(34, 139, 34)    ]
["Fuchsia"                  Fuchsia                 FUCHSIA                     fuchsia                     fuchsia                 FUCHSIA                 "FF00FF"    RGB(255, 0, 255)    ]
["Gainsboro"                Gainsboro               GAINSBORO                   gainsboro                   gainsboro               GAINSBORO               "DCDCDC"    RGB(220, 220, 220)  ]
["Ghost White"              GhostWhite              GHOST_WHITE                 ghost_white                 ghostwhite              GHOSTWHITE              "F8F8FF"    RGB(248, 248, 255)  ]
["Gold"                     Gold                    GOLD                        gold                        gold                    GOLD                    "FFD700"    RGB(255, 215, 0)    ]
["Goldenrod"                Goldenrod               GOLDENROD                   goldenrod                   goldenrod               GOLDENROD               "DAA520"    RGB(218, 165, 32)   ]
["Gray"                     Gray                    GRAY                        gray                        gray                    GRAY                    "808080"    RGB(128, 128, 128)  ]
["Green"                    Green                   GREEN                       green                       green                   GREEN                   "008000"    RGB(0, 128, 0)      ]
["Green Yellow"             GreenYellow             GREEN_YELLOW                green_yellow                greenyellow             GREENYELLOW             "ADFF2F"    RGB(173, 255, 47)   ]
["Honeydew"                 Honeydew                HONEYDEW                    honeydew                    honeydew                HONEYDEW                "F0FFF0"    RGB(240, 255, 240)  ]
["Hot Pink"                 HotPink                 HOT_PINK                    hot_pink                    hotpink                 HOTPINK                 "FF69B4"    RGB(255, 105, 180)  ]
["Indian Red"               IndianRed               INDIAN_RED                  indian_red                  indianred               INDIANRED               "CD5C5C"    RGB(205, 92, 92)    ]
["Indigo"                   Indigo                  INDIGO                      indigo                      indigo                  INDIGO                  "4B0082"    RGB(75, 0, 130)     ]
["Ivory"                    Ivory                   IVORY                       ivory                       ivory                   IVORY                   "FFFFF0"    RGB(255, 255, 240)  ]
["Khaki"                    Khaki                   KHAKI                       khaki                       khaki                   KHAKI                   "F0E68C"    RGB(240, 230, 140)  ]
["Lavender"                 Lavender                LAVENDER                    lavender                    lavender                LAVENDER                "E6E6FA"    RGB(230, 230, 250)  ]
["Lavender Blush"           LavenderBlush           LAVENDER_BLUSH              lavender_blush              lavenderblush           LAVENDERBLUSH           "FFF0F5"    RGB(255, 240, 245)  ]
["Lawn Green"               LawnGreen               LAWN_GREEN                  lawn_green                  lawngreen               LAWNGREEN               "7CFC00"    RGB(124, 252, 0)    ]
["Lemon Chiffon"            LemonChiffon            LEMON_CHIFFON               lemon_chiffon               lemonchiffon            LEMONCHIFFON            "FFFACD"    RGB(255, 250, 205)  ]
["Light Blue"               LightBlue               LIGHT_BLUE                  light_blue                  lightblue               LIGHTBLUE               "ADD8E6"    RGB(173, 216, 230)  ]
["Light Coral"              LightCoral              LIGHT_CORAL                 light_coral                 lightcoral              LIGHTCORAL              "F08080"    RGB(240, 128, 128)  ]
["Light Cyan"               LightCyan               LIGHT_CYAN                  light_cyan                  lightcyan               LIGHTCYAN               "E0FFFF"    RGB(224, 255, 255)  ]
["Light Goldenrod Yellow"   LightGoldenrodYellow    LIGHT_GOLDENROD_YELLOW      light_goldenrod_yellow      lightgoldenrodyellow    LIGHTGOLDENRODYELLOW    "FAFAD2"    RGB(250, 250, 210)  ]
["Light Gray"               LightGray               LIGHT_GRAY                  light_gray                  lightgray               LIGHTGRAY               "D3D3D3"    RGB(211, 211, 211)  ]
["Light Green"              LightGreen              LIGHT_GREEN                 light_green                 lightgreen              LIGHTGREEN              "90EE90"    RGB(144, 238, 144)  ]
["Light Pink"               LightPink               LIGHT_PINK                  light_pink                  lightpink               LIGHTPINK               "FFB6C1"    RGB(255, 182, 193)  ]
["Light Salmon"             LightSalmon             LIGHT_SALMON                light_salmon                lightsalmon             LIGHTSALMON             "FFA07A"    RGB(255, 160, 122)  ]
["Light Sea Green"          LightSeaGreen           LIGHT_SEA_GREEN             light_sea_green             lightseagreen           LIGHTSEAGREEN           "20B2AA"    RGB(32, 178, 170)   ]
["Light Sky Blue"           LightSkyBlue            LIGHT_SKY_BLUE              light_sky_blue              lightskyblue            LIGHTSKYBLUE            "87CEFA"    RGB(135, 206, 250)  ]
["Light Slate Gray"         LightSlateGray          LIGHT_SLATE_GRAY            light_slate_gray            lightslategray          LIGHTSLATEGRAY          "778899"    RGB(119, 136, 153)  ]
["Light Steel Blue"         LightSteelBlue          LIGHT_STEEL_BLUE            light_steel_blue            lightsteelblue          LIGHTSTEELBLUE          "B0C4DE"    RGB(176, 196, 222)  ]
["Light Yellow"             LightYellow             LIGHT_YELLOW                light_yellow                lightyellow             LIGHTYELLOW             "FFFFE0"    RGB(255, 255, 224)  ]
["Lime"                     Lime                    LIME                        lime                        lime                    LIME                    "00FF00"    RGB(0, 255, 0)      ]
["Lime Green"               LimeGreen               LIME_GREEN                  lime_green                  limegreen               LIMEGREEN               "32CD32"    RGB(50, 205, 50)    ]
["Linen"                    Linen                   LINEN                       linen                       linen                   LINEN                   "FAF0E6"    RGB(250, 240, 230)  ]
["Magenta"                  Magenta                 MAGENTA                     magenta                     magenta                 MAGENTA                 "FF00FF"    RGB(255, 0, 255)    ]
["Maroon"                   Maroon                  MAROON                      maroon                      maroon                  MAROON                  "800000"    RGB(128, 0, 0)      ]
["Medium Aquamarine"        MediumAquamarine        MEDIUM_AQUAMARINE           medium_aquamarine           mediumaquamarine        MEDIUMAQUAMARINE        "66CDAA"    RGB(102, 205, 170)  ]
["Medium Blue"              MediumBlue              MEDIUM_BLUE                 medium_blue                 mediumblue              MEDIUMBLUE              "0000CD"    RGB(0, 0, 205)      ]
["Medium Orchid"            MediumOrchid            MEDIUM_ORCHID               medium_orchid               mediumorchid            MEDIUMORCHID            "BA55D3"    RGB(186, 85, 211)   ]
["Medium Purple"            MediumPurple            MEDIUM_PURPLE               medium_purple               mediumpurple            MEDIUMPURPLE            "9370DB"    RGB(147, 112, 219)  ]
["Medium Sea Green"         MediumSeaGreen          MEDIUM_SEA_GREEN            medium_sea_green            mediumseagreen          MEDIUMSEAGREEN          "3CB371"    RGB(60, 179, 113)   ]
["Medium Slate Blue"        MediumSlateBlue         MEDIUM_SLATE_BLUE           medium_slate_blue           mediumslateblue         MEDIUMSLATEBLUE         "7B68EE"    RGB(123, 104, 238)  ]
["Medium Spring Green"      MediumSpringGreen       MEDIUM_SPRING_GREEN         medium_spring_green         mediumspringgreen       MEDIUMSPRINGGREEN       "00FA9A"    RGB(0, 250, 154)    ]
["Medium Turquoise"         MediumTurquoise         MEDIUM_TURQUOISE            medium_turquoise            mediumturquoise         MEDIUMTURQUOISE         "48D1CC"    RGB(72, 209, 204)   ]
["Medium Violet Red"        MediumVioletRed         MEDIUM_VIOLET_RED           medium_violet_red           mediumvioletred         MEDIUMVIOLETRED         "C71585"    RGB(199, 21, 133)   ]
["Midnight Blue"            MidnightBlue            MIDNIGHT_BLUE               midnight_blue               midnightblue            MIDNIGHTBLUE            "191970"    RGB(25, 25, 112)    ]
["Mint Cream"               MintCream               MINT_CREAM                  mint_cream                  mintcream               MINTCREAM               "F5FFFA"    RGB(245, 255, 250)  ]
["Misty Rose"               MistyRose               MISTY_ROSE                  misty_rose                  mistyrose               MISTYROSE               "FFE4E1"    RGB(255, 228, 225)  ]
["Moccasin"                 Moccasin                MOCCASIN                    moccasin                    moccasin                MOCCASIN                "FFE4B5"    RGB(255, 228, 181)  ]
["Navajo White"             NavajoWhite             NAVAJO_WHITE                navajo_white                navajowhite             NAVAJOWHITE             "FFDEAD"    RGB(255, 222, 173)  ]
["Navy"                     Navy                    NAVY                        navy                        navy                    NAVY                    "000080"    RGB(0, 0, 128)      ]
["Old Lace"                 OldLace                 OLD_LACE                    old_lace                    oldlace                 OLDLACE                 "FDF5E6"    RGB(253, 245, 230)  ]
["Olive"                    Olive                   OLIVE                       olive                       olive                   OLIVE                   "808000"    RGB(128, 128, 0)    ]
["Olive Drab"               OliveDrab               OLIVE_DRAB                  olive_drab                  olivedrab               OLIVEDRAB               "6B8E23"    RGB(107, 142, 35)   ]
["Orange"                   Orange                  ORANGE                      orange                      orange                  ORANGE                  "FFA500"    RGB(255, 165, 0)    ]
["Orange Red"               OrangeRed               ORANGE_RED                  orange_red                  orangered               ORANGERED               "FF4500"    RGB(255, 69, 0)     ]
["Orchid"                   Orchid                  ORCHID                      orchid                      orchid                  ORCHID                  "DA70D6"    RGB(218, 112, 214)  ]
["Pale Goldenrod"           PaleGoldenrod           PALE_GOLDENROD              pale_goldenrod              palegoldenrod           PALEGOLDENROD           "EEE8AA"    RGB(238, 232, 170)  ]
["Pale Green"               PaleGreen               PALE_GREEN                  pale_green                  palegreen               PALEGREEN               "98FB98"    RGB(152, 251, 152)  ]
["Pale Turquoise"           PaleTurquoise           PALE_TURQUOISE              pale_turquoise              paleturquoise           PALETURQUOISE           "AFEEEE"    RGB(175, 238, 238)  ]
["Pale Violet Red"          PaleVioletRed           PALE_VIOLET_RED             pale_violet_red             palevioletred           PALEVIOLETRED           "DB7093"    RGB(219, 112, 147)  ]
["Papaya Whip"              PapayaWhip              PAPAYA_WHIP                 papaya_whip                 papayawhip              PAPAYAWHIP              "FFEFD5"    RGB(255, 239, 213)  ]
["Peach Puff"               PeachPuff               PEACH_PUFF                  peach_puff                  peachpuff               PEACHPUFF               "FFDAB9"    RGB(255, 218, 185)  ]
["Peru"                     Peru                    PERU                        peru                        peru                    PERU                    "CD853F"    RGB(205, 133, 63)   ]
["Pink"                     Pink                    PINK                        pink                        pink                    PINK                    "FFC0CB"    RGB(255, 192, 203)  ]
["Plum"                     Plum                    PLUM                        plum                        plum                    PLUM                    "DDA0DD"    RGB(221, 160, 221)  ]
["Powder Blue"              PowderBlue              POWDER_BLUE                 powder_blue                 powderblue              POWDERBLUE              "B0E0E6"    RGB(176, 224, 230)  ]
["Purple"                   Purple                  PURPLE                      purple                      purple                  PURPLE                  "800080"    RGB(128, 0, 128)    ]
["Red"                      Red                     RED                         red                         red                     RED                     "FF0000"    RGB(255, 0, 0)      ]
["Rosy Brown"               RosyBrown               ROSY_BROWN                  rosy_brown                  rosybrown               ROSYBROWN               "BC8F8F"    RGB(188, 143, 143)  ]
["Royal Blue"               RoyalBlue               ROYAL_BLUE                  royal_blue                  royalblue               ROYALBLUE               "4169E1"    RGB(65, 105, 225)   ]
["Saddle Brown"             SaddleBrown             SADDLE_BROWN                saddle_brown                saddlebrown             SADDLEBROWN             "8B4513"    RGB(139, 69, 19)    ]
["Salmon"                   Salmon                  SALMON                      salmon                      salmon                  SALMON                  "FA8072"    RGB(250, 128, 114)  ]
["Sandy Brown"              SandyBrown              SANDY_BROWN                 sandy_brown                 sandybrown              SANDYBROWN              "F4A460"    RGB(244, 164, 96)   ]
["Sea Green"                SeaGreen                SEA_GREEN                   sea_green                   seagreen                SEAGREEN                "2E8B57"    RGB(46, 139, 87)    ]
["Seashell"                 Seashell                SEASHELL                    seashell                    seashell                SEASHELL                "FFF5EE"    RGB(255, 245, 238)  ]
["Sienna"                   Sienna                  SIENNA                      sienna                      sienna                  SIENNA                  "A0522D"    RGB(160, 82, 45)    ]
["Silver"                   Silver                  SILVER                      silver                      silver                  SILVER                  "C0C0C0"    RGB(192, 192, 192)  ]
["Sky Blue"                 SkyBlue                 SKY_BLUE                    sky_blue                    skyblue                 SKYBLUE                 "87CEEB"    RGB(135, 206, 235)  ]
["Slate Blue"               SlateBlue               SLATE_BLUE                  slate_blue                  slateblue               SLATEBLUE               "6A5ACD"    RGB(106, 90, 205)   ]
["Slate Gray"               SlateGray               SLATE_GRAY                  slate_gray                  slategray               SLATEGRAY               "708090"    RGB(112, 128, 144)  ]
["Snow"                     Snow                    SNOW                        snow                        snow                    SNOW                    "FFFAFA"    RGB(255, 250, 250)  ]
["Spring Green"             SpringGreen             SPRING_GREEN                spring_green                springgreen             SPRINGGREEN             "00FF7F"    RGB(0, 255, 127)    ]
["Steel Blue"               SteelBlue               STEEL_BLUE                  steel_blue                  steelblue               STEELBLUE               "4682B4"    RGB(70, 130, 180)   ]
["Tan"                      Tan                     TAN                         tan                         tan                     TAN                     "D2B48C"    RGB(210, 180, 140)  ]
["Teal"                     Teal                    TEAL                        teal                        teal                    TEAL                    "008080"    RGB(0, 128, 128)    ]
["Thistle"                  Thistle                 THISTLE                     thistle                     thistle                 THISTLE                 "D8BFD8"    RGB(216, 191, 216)  ]
["Tomato"                   Tomato                  TOMATO                      tomato                      tomato                  TOMATO                  "FF6347"    RGB(255, 99, 71)    ]
["Turquoise"                Turquoise               TURQUOISE                   turquoise                   turquoise               TURQUOISE               "40E0D0"    RGB(64, 224, 208)   ]
["Violet"                   Violet                  VIOLET                      violet                      violet                  VIOLET                  "EE82EE"    RGB(238, 130, 238)  ]
["Wheat"                    Wheat                   WHEAT                       wheat                       wheat                   WHEAT                   "F5DEB3"    RGB(245, 222, 179)  ]
["White"                    White                   WHITE                       white                       white                   WHITE                   "FFFFFF"    RGB(255, 255, 255)  ]
["White Smoke"              WhiteSmoke              WHITE_SMOKE                 white_smoke                 whitesmoke              WHITESMOKE              "F5F5F5"    RGB(245, 245, 245)  ]
["Yellow"                   Yellow                  YELLOW                      yellow                      yellow                  YELLOW                  "FFFF00"    RGB(255, 255, 0)    ]
["Yellow Green"             YellowGreen             YELLOW_GREEN                yellow_green                yellowgreen             YELLOWGREEN             "9ACD32"    RGB(154, 205, 50)   ]
        }
    };
}